[project]
name = "ha-run-chicken"
description = "Add your description here"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bluetooth-sensor-state-data>=1.9.0",
    "colorlog==6.10.1",
    "crc8>=0.2.1",
    "homeassistant==2025.2.4",
    "pip>=21.3.1",
    "pre-commit>=4.5.0",
    "ruff==0.14.9",
    "sensor-state-data>=2.20.0",
    "uv-dynamic-versioning>=0.6.0",
]

[build-system]
requires = [
    "hatchling>=1.25.0",
    "uv-dynamic-versioning>=0.6.0",
]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build]
include = [
    "custom_components",
    "scripts/inject_manifest_version.py",
]

[tool.uv-dynamic-versioning]
fallback-version = "0.0.0"

[tool.hatch.build.hooks.custom]
path = "scripts/inject_manifest_version.py"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { git = { commit = true, tags = true }}]
