[project]
name = "ha-run-chicken"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bluetooth-sensor-state-data>=1.9.0",
    "colorlog==6.10.1",
    "crc8>=0.2.1",
    "homeassistant==2025.2.4",
    "pip>=21.3.1",
    "ruff==0.14.6",
    "sensor-state-data>=2.20.0",
]
